fix/338: add Util function to fetch primary category
globeandmail/sophi-for-wordpress pull request #350
Opened 2022-10-30 15:07 UTC by Sidsector9

### Description of the Change

Closes #

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

### Credits

Props @Sidsector9

2022-10-31 15:01 UTC, cadic requested changes
The code looks good. I have a concern about the 4th Unit test added.

2022-10-31 15:01 UTC, cadic commented on tests/phpunit/test-tools/Utils_Tests.php
> +	public function test_get_primary_category__custom_category__yoast_activated() {
Looks like this last test is a full-copy of the previous one (except the category name) and does not test any alternative workflow.

2022-10-31 20:02 UTC, Sidsector9 commented on tests/phpunit/test-tools/Utils_Tests.php
> +	public function test_get_primary_category__custom_category__yoast_activated() {
you're correct!

2022-11-01 05:25 UTC, cadic approved these changes

2022-11-01 13:24 UTC, jeffpaul commented
Holding off on merge here as we're awaiting Sophi team approval on the pending 1.3.0 release and I'd prefer to not change any additional code.  Once 1.3.0 is released, I'll merge this in so we can deploy/test and prepare as part of a 1.3.1/1.4.0 release.

2022-11-03 19:01 UTC, merged